In [ ]:
import pandas as pd


year_start = 2015
year_end   = 2016
months     = [1]  

base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"

frames = []
for year in range(year_start, year_end + 1):
    for month in months:
        url = base_url.format(year=year, month=month)
        pd_temp = pd.read_parquet(url)
        pd_temp.columns = pd_temp.columns.str.lower()
        frames.append(pd_temp)

df = pd.concat(frames, ignore_index=True)
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2015-01-01 00:11:33,2015-01-01 00:16:48,1,1.0,1,N,41,166,1,5.7,0.5,0.5,1.40,0.0,0.0,8.40,None,None
1,1,2015-01-01 00:18:24,2015-01-01 00:24:20,1,0.9,1,N,166,238,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None
2,1,2015-01-01 00:26:19,2015-01-01 00:41:06,1,3.5,1,N,238,162,1,13.2,0.5,0.5,2.90,0.0,0.0,17.40,None,None
3,1,2015-01-01 00:45:26,2015-01-01 00:53:20,1,2.1,1,N,162,263,1,8.2,0.5,0.5,2.37,0.0,0.0,11.87,None,None
4,1,2015-01-01 00:59:21,2015-01-01 01:05:24,1,1.0,1,N,236,141,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None

In [16]:
base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-10.parquet"

df_2015 = pd.read_parquet(base_url.format(year=2015))
df_2025 = pd.read_parquet(base_url.format(year=2025))

df_2015.columns = df_2015.columns.str.lower()
df_2025.columns = df_2025.columns.str.lower()


cols_2015 = set(df_2015.columns)
cols_2025 = set(df_2025.columns)

print("Columnas 2015:", sorted(df_2015.columns.tolist()))
print()
print("Columnas 2025:", sorted(df_2025.columns.tolist()))
print()
print("Solo en 2015:", sorted(cols_2015 - cols_2025))
print("Solo en 2025:", sorted(cols_2025 - cols_2015))
print("En ambas:    ", sorted(cols_2015 & cols_2025))

Columnas 2015: ['airport_fee', 'congestion_surcharge', 'dolocationid', 'extra', 'fare_amount', 'improvement_surcharge', 'mta_tax', 'passenger_count', 'payment_type', 'pulocationid', 'ratecodeid', 'store_and_fwd_flag', 'tip_amount', 'tolls_amount', 'total_amount', 'tpep_dropoff_datetime', 'tpep_pickup_datetime', 'trip_distance', 'vendorid']

Columnas 2025: ['airport_fee', 'cbd_congestion_fee', 'congestion_surcharge', 'dolocationid', 'extra', 'fare_amount', 'improvement_surcharge', 'mta_tax', 'passenger_count', 'payment_type', 'pulocationid', 'ratecodeid', 'store_and_fwd_flag', 'tip_amount', 'tolls_amount', 'total_amount', 'tpep_dropoff_datetime', 'tpep_pickup_datetime', 'trip_distance', 'vendorid']

Solo en 2015: []
Solo en 2025: ['cbd_congestion_fee']
En ambas:     ['airport_fee', 'congestion_surcharge', 'dolocationid', 'extra', 'fare_amount', 'improvement_surcharge', 'mta_tax', 'passenger_count', 'payment_type', 'pulocationid', 'ratecodeid', 'store_and_fwd_flag', 'tip_amount', 'tolls_amount', 'total_amount', 'tpep_dropoff_datetime', 'tpep_pickup_datetime', 'trip_distance', 'vendorid']

In [13]:
year_start = 2015
year_end   = 2025 
months     = range(1, 13) 

base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"

urls = []
for year in range(year_start, year_end + 1):
    for month in months:
        urls.append(base_url.format(year=year, month=month))
        
print(urls)

['https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2015-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2016-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2018-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2019-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-12.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-02.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-03.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-04.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-05.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-06.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-07.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-08.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-09.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-10.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-11.parquet', 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-12.parquet']

In [1]:
import pandas as pd


year_start = 2015
year_end   = 2025
months     = [1]  

base_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month:02d}.parquet"

frames = []
for year in range(year_start, year_end + 1):
    for month in months:
        url = base_url.format(year=year, month=month)
        pd_temp = pd.read_parquet(url)
        pd_temp.columns = pd_temp.columns.str.lower()
        frames.append(pd_temp)

one_month_year = pd.concat(frames, ignore_index=True)
one_month_year.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,cbd_congestion_fee
0,1,2015-01-01 00:11:33,2015-01-01 00:16:48,1.0,1.0,1.0,N,41,166,1,5.7,0.5,0.5,1.40,0.0,0.0,8.40,None,None,NaN
1,1,2015-01-01 00:18:24,2015-01-01 00:24:20,1.0,0.9,1.0,N,166,238,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None,NaN
2,1,2015-01-01 00:26:19,2015-01-01 00:41:06,1.0,3.5,1.0,N,238,162,1,13.2,0.5,0.5,2.90,0.0,0.0,17.40,None,None,NaN
3,1,2015-01-01 00:45:26,2015-01-01 00:53:20,1.0,2.1,1.0,N,162,263,1,8.2,0.5,0.5,2.37,0.0,0.0,11.87,None,None,NaN
4,1,2015-01-01 00:59:21,2015-01-01 01:05:24,1.0,1.0,1.0,N,236,141,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None,NaN

In [3]:
one_month_year.describe()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,cbd_congestion_fee,year
count,6.955955e+07,69559550,69559550,6.854353e+07,6.955955e+07,6.854353e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,6.955955e+07,3.475226e+06,6.955955e+07
mean,1.601874e+00,2018-05-13 04:37:49.446375,2018-05-13 04:53:02.615903,1.575061e+00,5.337742e+00,1.180230e+00,1.643709e+02,1.623318e+02,1.294827e+00,1.309769e+01,5.819176e-01,4.947332e-01,2.051649e+00,3.210596e-01,3.879273e-01,1.744235e+01,4.834093e-01,2.018319e+03
min,1.000000e+00,2001-01-05 11:45:23,2001-01-05 11:52:05,0.000000e+00,-3.062000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.238000e+03,-7.900000e+01,-5.000000e-01,-2.208000e+02,-1.269400e+02,-1.000000e+00,-1.242300e+03,-7.500000e-01,2.001000e+03
25%,1.000000e+00,2016-01-14 08:08:12.250000,2016-01-14 08:22:12,1.000000e+00,9.800000e-01,1.000000e+00,1.160000e+02,1.120000e+02,1.000000e+00,6.500000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,3.000000e-01,9.120000e+00,0.000000e+00,2.016000e+03
50%,2.000000e+00,2018-01-07 00:56:28.500000,2018-01-07 01:12:23.500000,1.000000e+00,1.610000e+00,1.000000e+00,1.620000e+02,1.620000e+02,1.000000e+00,9.500000e+00,0.000000e+00,5.000000e-01,1.500000e+00,0.000000e+00,3.000000e-01,1.280000e+01,7.500000e-01,2.018000e+03
75%,2.000000e+00,2020-01-13 08:23:54,2020-01-13 08:42:31,2.000000e+00,3.000000e+00,1.000000e+00,2.340000e+02,2.340000e+02,2.000000e+00,1.450000e+01,5.000000e-01,5.000000e-01,2.660000e+00,0.000000e+00,3.000000e-01,1.930000e+01,7.500000e-01,2.020000e+03
max,7.000000e+00,2088-01-24 00:25:39,2088-01-24 07:28:25,9.000000e+00,1.542000e+07,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,8.633721e+05,6.488700e+02,8.970000e+01,3.950589e+06,3.288000e+03,1.000000e+00,3.950612e+06,7.500000e-01,2.088000e+03
std,5.015638e-01,NaN,NaN,1.221275e+00,4.365787e+03,3.641101e+00,6.625529e+01,7.045037e+01,5.176147e-01,1.752871e+02,1.012756e+00,6.646089e-02,4.736864e+02,1.755429e+00,2.495750e-01,5.051641e+02,3.619307e-01,2.936237e+00

In [2]:
# Valindando que años contiene la columna tpep_pickup_datetime
one_month_year['tpep_pickup_datetime'] = pd.to_datetime(one_month_year['tpep_pickup_datetime'])
one_month_year['year'] = one_month_year['tpep_pickup_datetime'].dt.year
one_month_year['year'].value_counts().sort_index()

year
2001           2
2002           7
2003           8
2008          52
2009         100
2015    12741035
2016    10905067
2017     9711046
2018     8760788
2019     7696305
2020     6404860
2021     1369776
2022     2463929
2023     3066738
2024     2964630
2025     3475205
2088           2
Name: count, dtype: int64

In [4]:
# verificamos la cantidad de nulos por columna
one_month_year.isna().sum()

vendorid                        0
tpep_pickup_datetime            0
tpep_dropoff_datetime           0
passenger_count           1016022
trip_distance                   0
ratecodeid                1016022
store_and_fwd_flag        1016022
pulocationid                    0
dolocationid                    0
payment_type                    0
fare_amount                     0
extra                           0
mta_tax                         0
tip_amount                      0
tolls_amount                    0
improvement_surcharge           3
total_amount                    0
congestion_surcharge     47989834
airport_fee              58412543
cbd_congestion_fee       66084324
year                            0
dtype: int64

In [6]:
# verificamos la cantidad de nulos por columna agrupados por año
nulos_por_columna_año = one_month_year.groupby('year').apply(lambda x: x.isna().sum())
nulos_por_columna_año

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,cbd_congestion_fee
year,,,,,,,,,,,,,,,,,,,,
2001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2
2002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,7
2003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,8,8
2008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,28,44,52
2009,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,61,89,100
2015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,12741035,12741035,12741035
2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10905067,10905067,10905067
2017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9711046,9711046,9711046
2018,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8760776,8760776,8760788
2019,0,0,0,28672,0,28672,28672,0,0,0,0,0,0,0,0,0,0,4884455,7696305,7696305
2020,0,0,0,65441,0,65441,65441,0,0,0,0,0,0,0,0,0,0,65441,6404860,6404860
2021,0,0,0,98352,0,98352,98352,0,0,0,0,0,0,0,0,0,0,98352,1369747,1369776
2022,0,0,0,71503,0,71503,71503,0,0,0,0,0,0,0,0,0,0,71503,71503,2463929
2023,0,0,0,71743,0,71743,71743,0,0,0,0,0,0,0,0,0,0,71743,71743,3066738
2024,0,0,0,140162,0,140162,140162,0,0,0,0,0,0,0,0,0,0,140162,140162,2964609
2025,0,0,0,540149,0,540149,540149,0,0,0,0,0,0,0,0,0,0,540149,540149,0
2088,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2